### PR TITLE
Add pre/post hooks support for compile and clean

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Can we publish a release? This is needed to resolve https://github.com/tuncer/re2/issues/13.

**Comment by tsloughter** [comment]
Have you tested it? I'll publish to hex if you verified it worked for
re2

## 

Tristan Sloughter
t@crashfast.com

On Thu, Jul 14, 2016, at 12:28 PM, Tuncer Ayaz wrote:

> Can we publish a release? This is needed to resolve tuncer/re2#13[1].
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].

Links:
1. https://github.com/tuncer/re2/issues/13
2. https://github.com/blt/port_compiler/pull/24#issuecomment-232767490
3. https://github.com/notifications/unsubscribe/AACNg42PULLImEUgUL7lbAD1QjqUTQoLks5qVo3wgaJpZM4JMsZN

**Comment by ghost** [comment]
Verified that compile and clean work in re2.

**Comment by ghost** [comment]
@tsloughter, ping?

**Comment by tsloughter** [comment]
I'll get this published today.

**Comment by tsloughter** [comment]
Published 1.3.0 https://hex.pm/packages/pc/1.3.0

**Comment by ghost** [comment]
Thanks.

**Pull request merged**
