### PR TITLE
remove use of lib_dir/2 bc it is deprecated in otp-27

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by gonzalobf** [comment]
Hey @tsloughter

Would be possible to get this PR merged and get new version released. OTP-27 was released today and your change totally removes the deprecation warning so I was wondering if it would be possible to get it soon.

Thank you :)

**Comment by tsloughter** [comment]
Oh, yes, sorry about that.

**Comment by gonzalobf** [comment]
Thank you :D

**Comment by lpgauth** [comment]
Thank you!

**Pull request merged**
